; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Bounce Game"
#define MyAppVersion "1.0"
#define MyAppPublisher "Mattias Ülejõe"
#define MyAppURL "https://github.com/qqqqq2d/bounce-game"
#define MyAppExeName "prog.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{551163AD-B71A-4D10-A62F-D55881920301}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=setup
SetupIconFile=C:\bounce-game\images\icon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\bounce-game\build\Release\{#MyAppExeName}"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\brotlicommon.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\brotlidec.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\bz2.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\FLAC.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\freetype.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\libpng16.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\ogg.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\OpenAL32.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\sfml-audio-2.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\sfml-graphics-2.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\sfml-system-2.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\sfml-window-2.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\zlib1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\vorbis.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\vorbisenc.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\build\Release\vorbisfile.dll"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "C:\bounce-game\fonts\*"; DestDir: "{app}\fonts"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\bounce-game\images\*"; DestDir: "{app}\images"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\bounce-game\sounds\*"; DestDir: "{app}\sounds"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon

;[Run]
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

